### ISSUE TITLE
Is there a script to visualize the Hybrid_ViT heatmap

### ISSUE THREAD

**Issue by mucunwuxian** [anguyen8/face-vit#2]
Thank you for your great work!

I would like to ask.
As the title says, is there a script to visualize the Hybrid_ViT heatmap?
Or is there a way to change the current script to visualize it?

I would especially like to know about the format of authentication based on similarity, as in test.py.
<img width="200" alt="image" src="https://github.com/anguyen8/face-vit/assets/9916906/cc64b1d0-15ba-4184-be68-aeda7b3c9dbe">

Best regards,

**Comment by anguyen8** [comment]
Hi @mucunwuxian , you can use [this script](https://github.com/anguyen8/face-vit/blob/main/visualize_vit_heatmap.py) to visualize the heatmaps.

Basically, it shows the cross attention, between the CLS embedding of image 1 vs. the patch embeddings from image 2, and vice versa.

**Comment by mucunwuxian** [comment]
@anguyen8
Thank you again for your reply!
I'll try using the information you provided too.👍
