### ISSUE TITLE
want to test on custom images

### ISSUE THREAD

**Issue by Raghucharan16** [anguyen8/face-vit#4]
First of all thanks for the great work. I'm having a specific use case in which i have to extract unique faces from 2 folder of faces. each folder contains multiple faces of different persons. [say person1's faces can exist more than once ] and same person1 's faces can be there in folder2 but with different side angles. like wise we can have multiple faces of different persons in the both folders now my task is to extract only unique faces from both folders and save them in another folder. for this i have to use face recognition libraries and I gave my try with deepface, face-recognition, insightface, and several state of art algorithms like VGG-Face, Facenet, Facenet512, Openface, Arcface, GhostFaceNet, Deepface, deepid, dlib and also tried insightface's arcface_torch models [buffalo_l, glint360k] and among these glinkt360k is performing well. I've got the south asian faces data to perform this. and it would be of great help if you tell how can i use these pretrained models for facial recognition tasks. I've followed this [link](https://github.com/deepinsight/insightface/tree/master/recognition/arcface_torch) and came to know that Vit based one is better one as it is trained on 42M images with 2M ID's. Thanks for the help.
![image](https://github.com/anguyen8/face-vit/assets/104614903/4fcc71e4-8638-4860-b6db-6c6b9f9637df)

**Comment by anguyen8** [comment]
Hi, I'm not sure what you are asking.

Could you please rephrase your question to be more specific?
Like most other face-identification libraries, our model takes in two images (a query and one from the gallery) and provide you a score, with which you can rank the gallery images and find those most similar to the query.

**Comment by Raghucharan16** [comment]
Could you provide a sample code for the above. [face recognition of 2 faces / images using your model.
