### ISSUE TITLE
missing txt file: lfw_test_pair.txt

### ISSUE THREAD

**Issue by nadiaparsell** [anguyen8/face-vit#5]
Hello, 

I have downloaded all of the material from the readme.md and I do not see lfw_test_pair.txt. I see casia_pair_112_2m.txt, casia_pair_112_label_2m.txt, and ms_celeb_pair_112_label2.txt. 

If there is anything else I need to have/to do to run test.py, please let me know. Thank you!

**Comment by anguyen8** [comment]
Hi @nadiaparsell 

Could you try this and see if it works?
https://github.com/ronghuaiyang/arcface-pytorch/blob/master/lfw_test_pair.txt
